Repository fli-iam/shanoir-ng, pull requests merged in 2023-05, with the labels that each got.

#1654 Quality bug fixes
  docker-compose/database/db-changes/datasets/0025_quality_control_in_import.sql
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/download/WADODownloaderService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/ImporterService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/controler/QualityCardApi.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/controler/QualityCardApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/controler/StudyCardApi.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/controler/StudyCardApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/dto/QualityCardResult.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/model/QualityCard.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/model/condition/StudyCardDICOMCondition.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/model/condition/StudyCardMetadataConditionWithCardinality.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/model/rule/QualityExaminationRule.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/service/CardsProcessingService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/service/QualityCardServiceImpl.java
  shanoir-ng-front/src/app/app-routing.module.ts
  shanoir-ng-front/src/app/app.component.ts
  shanoir-ng-front/src/app/breadcrumbs/breadcrumbs.service.ts
  shanoir-ng-front/src/app/quality-control/quality-control.component.css
  shanoir-ng-front/src/app/quality-control/quality-control.component.html
  shanoir-ng-front/src/app/quality-control/quality-control.component.ts
  shanoir-ng-front/src/app/shared/components/subject-study-list/subject-study-list.component.html
  shanoir-ng-front/src/app/shared/select/select.component.css
  shanoir-ng-front/src/app/shared/select/select.component.html
  shanoir-ng-front/src/app/shared/select/select.component.ts
  shanoir-ng-front/src/app/studies/study/study.component.html
  shanoir-ng-front/src/app/studies/study/study.component.ts
  shanoir-ng-front/src/app/studies/tree/study-node.component.ts
  shanoir-ng-front/src/app/study-cards/quality-card/quality-card.component.html
  shanoir-ng-front/src/app/study-cards/quality-card/quality-card.component.ts
  shanoir-ng-front/src/app/study-cards/shared/quality-card.dto.model.ts
  shanoir-ng-front/src/app/study-cards/shared/quality-card.dto.ts
  shanoir-ng-front/src/app/study-cards/shared/quality-card.model.ts
  shanoir-ng-front/src/app/study-cards/shared/quality-card.service.ts
  shanoir-ng-front/src/app/study-cards/study-card-rules/condition/condition.component.ts
  shanoir-ng-front/src/app/study-cards/study-card-rules/study-card-rule.component.html
  shanoir-ng-front/src/app/study-cards/study-card-rules/study-card-rule.component.ts
  shanoir-ng-front/src/app/study-cards/study-card-rules/study-card-rules.component.html
  shanoir-ng-front/src/app/subjects/tree/subject-node.component.html
  shanoir-ng-front/src/app/tree/tree.model.ts
  shanoir-ng-front/src/app/utils/app.utils.ts
  shanoir-ng-ms-common/src/main/java/org/shanoir/ng/shared/exception/PacsException.java
Labels: BUGFIX, WorkInProgress

#1690 [Fli iam#1474] Delete from tree nodes
  shanoir-ng-front/src/app/acquisition-equipments/tree/equipment-node.component.html
  shanoir-ng-front/src/app/acquisition-equipments/tree/equipment-node.component.ts
  shanoir-ng-front/src/app/centers/tree/center-node.component.html
  shanoir-ng-front/src/app/centers/tree/center-node.component.ts
  shanoir-ng-front/src/app/dataset-acquisitions/tree/dataset-acquisition-node.component.html
  shanoir-ng-front/src/app/dataset-acquisitions/tree/dataset-acquisition-node.component.ts
  shanoir-ng-front/src/app/datasets/tree/dataset-node.component.html
  shanoir-ng-front/src/app/datasets/tree/dataset-node.component.ts
  shanoir-ng-front/src/app/datasets/tree/processing-node.component.html
  shanoir-ng-front/src/app/datasets/tree/processing-node.component.ts
  shanoir-ng-front/src/app/datasets/tree/simple-dataset-node.component.html
  shanoir-ng-front/src/app/datasets/tree/simple-dataset-node.component.ts
  shanoir-ng-front/src/app/examinations/tree/examination-node.component.html
  shanoir-ng-front/src/app/examinations/tree/examination-node.component.ts
  shanoir-ng-front/src/app/shared/components/entity/entity.abstract.service.ts
  shanoir-ng-front/src/app/shared/components/entity/entity.component.abstract.ts
  shanoir-ng-front/src/app/studies/study/study.component.html
  shanoir-ng-front/src/app/studies/tree/reverse-study-node.component.ts
  shanoir-ng-front/src/app/studies/tree/study-node.component.html
  shanoir-ng-front/src/app/studies/tree/study-node.component.ts
  shanoir-ng-front/src/app/study-cards/tree/study-card-node.component.html
  shanoir-ng-front/src/app/study-cards/tree/study-card-node.component.ts
  shanoir-ng-front/src/app/subjects/subject/subject.component.html
  shanoir-ng-front/src/app/subjects/tree/reverse-subject-node.component.html
  shanoir-ng-front/src/app/subjects/tree/reverse-subject-node.component.ts
  shanoir-ng-front/src/app/subjects/tree/subject-node.component.html
  shanoir-ng-front/src/app/subjects/tree/subject-node.component.ts
  shanoir-ng-front/src/app/tree/tree.model.ts
Labels: feature, REVIEWABLE

#1634 shanoir-issue#1625: fix bug - allow only centers of the study for whi…
  shanoir-ng-front/src/app/acquisition-equipments/acquisition-equipment/acquisition-equipment.component.ts
  shanoir-ng-front/src/app/import/clinical-context/clinical-context.abstract.component.ts
  shanoir-ng-front/src/app/study-cards/study-card/study-card.component.ts
Labels: BUGFIX, REVIEWABLE

#1696 [fli-iam#1695] Manage listing including related datasets
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/controler/ExaminationApi.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/controler/ExaminationApiController.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/examination/ExaminationApiControllerTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/examination/ExaminationApiSecurityTest.java
  shanoir-ng-front/src/app/examinations/shared/examination.service.ts
  shanoir-ng-front/src/app/studies/tree/study-tree.component.ts
Labels: blocking, BUGFIX, REVIEWABLE

#1699 [fli-iam#1671] Optimize preclinical subjects loading
  shanoir-ng-front/src/app/preclinical/animalSubject/list/animalSubject-list.component.ts
  shanoir-ng-front/src/app/preclinical/animalSubject/shared/animalSubject.service.ts
  shanoir-ng-front/src/app/preclinical/animalSubject/shared/preclinicalSubject.model.ts
  shanoir-ng-front/src/app/subjects/shared/subject.service.ts
  shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/subjects/AnimalSubjectApi.java
  shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/subjects/AnimalSubjectApiController.java
  shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/subjects/AnimalSubjectRepository.java
  shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/subjects/AnimalSubjectService.java
  shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/subjects/AnimalSubjectServiceImpl.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/controler/SubjectApi.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/controler/SubjectApiController.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/repository/SubjectRepository.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/service/SubjectService.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/service/SubjectServiceImpl.java
  shanoir-ng-studies/src/test/java/org/shanoir/ng/subject/SubjectApiSecurityTest.java
Labels: performance, REVIEWABLE

#1707 [fli-iam#1694] Use cache in github workflow
  .github/workflows/maven.yml
Labels: REVIEWABLE

#1704 [fli-iam#1688] Check if linked study card before deleting equipment
  shanoir-ng-front/src/app/acquisition-equipments/acquisition-equipment-list/acquisition-equipment-list.component.ts
  shanoir-ng-front/src/app/acquisition-equipments/acquisition-equipment/acquisition-equipment.component.ts
  shanoir-ng-front/src/app/acquisition-equipments/shared/acquisition-equipment.service.ts
  shanoir-ng-front/src/app/shared/components/entity/entity-list.component.abstract.ts
  shanoir-ng-front/src/app/shared/components/entity/entity.abstract.service.ts
  shanoir-ng-front/src/app/shared/models/error.model.ts
  shanoir-ng-front/src/app/study-cards/shared/study-card.service.ts
Labels: REVIEWABLE

#1640 shanoir-issue#1635: move schema.org DataCatalog to welcome page (used to be in login page)
  docker-compose/keycloak/themes/shanoir-theme/login/template.ftl
  docker-compose/nginx/entrypoint
  shanoir-ng-front/src/index.html
Labels: feature, REVIEWABLE

#1697 [fli-iam#1662] Add default pipeline execution name
  shanoir-ng-front/src/app/processing/execution/execution.component.html
  shanoir-ng-front/src/app/processing/execution/execution.component.ts
Labels: feature, REVIEWABLE

#1714 Locks in studies
  shanoir-ng-front/src/app/app-routing.module.ts
  shanoir-ng-front/src/app/shared/components/table/table.component.html
  shanoir-ng-front/src/app/studies/study-list/study-list.component.ts
  shanoir-ng-front/src/app/study-cards/apply-study-card-on/apply-study-card-on.component.css
  shanoir-ng-front/src/app/study-cards/apply-study-card-on/apply-study-card-on.component.ts
Labels: REVIEWABLE

#1709 shanoir-issue#1679: only allow password change for authenticated user + change keycloak url
  shanoir-ng-front/src/app/users/user/user.component.html
  shanoir-ng-front/src/app/users/user/user.component.ts
Labels: frontend, REVIEWABLE

#1594 shanoir-issue#1588: fixed center field while creating a new study + …
  shanoir-ng-front/src/app/shared/select/select.component.css
  shanoir-ng-front/src/app/shared/select/select.component.html
  shanoir-ng-front/src/app/shared/select/select.component.ts
  shanoir-ng-front/src/app/studies/study/study.component.html
  shanoir-ng-front/src/app/studies/study/study.component.ts
Labels: BUGFIX, WorkInProgress
