Repository fli-iam/shanoir-ng, pull requests merged in 2023-08, with the labels that each got.

#1786 #1783-Solr update after import + study card
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/service/DatasetAcquisitionService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/service/DatasetAcquisitionServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/ImporterService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/service/SolrService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/service/SolrServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/controler/StudyCardApiController.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/datasetacquisition/service/ImporterServiceTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/studycard/StudyCardApiControllerTest.java
Labels: REVIEWABLE

#1788 MS Import: better error/ignore management + update to dcm4che3 v5.30.0
  docker-compose/import/Dockerfile
  shanoir-ng-anonymization/pom.xml
  shanoir-ng-back/pom.xml
  shanoir-ng-datasets/pom.xml
  shanoir-ng-exchange/pom.xml
  shanoir-ng-import/pom.xml
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dcm2nii/DatasetsCreatorAndNIfTIConverterService.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/DicomDirToModelService.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/DicomSerieAndInstanceAnalyzer.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/ImagesCreatorAndDicomFileAnalyzerService.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/ImportJobConstructorService.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/query/QueryPACSService.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/model/Serie.java
  shanoir-ng-import/src/test/java/org/shanoir/ng/importer/ImporterApiControllerTest.java
Labels: REVIEWABLE

#1809 [Fli iam#1719] Details for study storage volume
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/configuration/amqp/RabbitMQDatasetsService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApi.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/dto/StudyStorageVolumeDTO.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/dto/VolumeByFormatDTO.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/repository/DatasetRepository.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/security/DatasetSecurityService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationServiceImpl.java
  shanoir-ng-front/src/app/acquisition-equipments/acquisition-equipment-list/acquisition-equipment-list.component.ts
  shanoir-ng-front/src/app/centers/center-list/center-list.component.ts
  shanoir-ng-front/src/app/datasets/shared/dataset.dto.ts
  shanoir-ng-front/src/app/datasets/shared/dataset.service.ts
  shanoir-ng-front/src/app/enum/dataset-expression-format.enum.ts
  shanoir-ng-front/src/app/shared/components/entity/entity.abstract.service.ts
  shanoir-ng-front/src/app/shared/components/table/column.definition.type.ts
  shanoir-ng-front/src/app/shared/components/table/table.component.html
  shanoir-ng-front/src/app/shared/multi-select-table/multi-select-table.component.ts
  shanoir-ng-front/src/app/studies/shared/study.dto.ts
  shanoir-ng-front/src/app/studies/shared/study.model.ts
  shanoir-ng-front/src/app/studies/shared/study.service.ts
  shanoir-ng-front/src/app/studies/study-list/study-list.component.ts
  shanoir-ng-front/src/app/studies/study/study.component.css
  shanoir-ng-front/src/app/studies/study/study.component.html
  shanoir-ng-front/src/app/studies/study/study.component.ts
  shanoir-ng-front/src/app/users/user-list/user-list.component.ts
  shanoir-ng-ms-common/src/main/java/org/shanoir/ng/shared/configuration/RabbitMQConfiguration.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/controler/StudyApi.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/controler/StudyApiController.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/dto/DatasetExpressionFormat.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/dto/StudyDTO.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/dto/StudyStorageVolumeDTO.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/dto/VolumeByFormatDTO.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/dto/mapper/StudyMapper.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/security/StudySecurityService.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/service/StudyService.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/service/StudyServiceImpl.java
  shanoir-ng-studies/src/main/resources/application.yml
  shanoir-ng-studies/src/test/java/org/shanoir/ng/study/StudyApiSecurityTest.java
Labels: REVIEWABLE

#1833 #1829-EEG-import-bug - Use rabbitMQ
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/controler/DatasetAcquisitionApi.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/controler/DatasetAcquisitionApiController.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterApiController.java
  shanoir-ng-import/src/test/java/org/shanoir/ng/importer/ImporterApiControllerTest.java
  shanoir-ng-ms-common/src/main/java/org/shanoir/ng/shared/configuration/RabbitMQConfiguration.java
Labels: REVIEWABLE

#1815 [fli-iam#1813] Ignore animal_subject linked to non-existing subject
  docker-compose/database/db-changes/studies/0017_add_subject_indexes.sql
  shanoir-ng-front/src/app/preclinical/animalSubject/list/animalSubject-list.component.ts
  shanoir-ng-front/src/app/preclinical/animalSubject/shared/animalSubject.service.ts
  shanoir-ng-front/src/app/preclinical/utils/preclinical.utils.ts
  shanoir-ng-ms-common/src/main/java/org/shanoir/ng/shared/configuration/RabbitMQConfiguration.java
  shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/extra_data/ExtraDataApiController.java
  shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/subjects/controller/AnimalSubjectApi.java
  shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/subjects/controller/AnimalSubjectApiController.java
  shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/subjects/model/AnimalSubject.java
  shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/subjects/repository/AnimalSubjectRepository.java
  shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/subjects/service/AnimalSubjectService.java
  shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/subjects/service/AnimalSubjectServiceImpl.java
  shanoir-ng-preclinical/src/test/java/org/shanoir/ng/preclinical/examination_extradata/ExtraDataApiControllerTest.java
  shanoir-ng-preclinical/src/test/java/org/shanoir/ng/preclinical/subjects/AnimalSubjectApiControllerTest.java
  shanoir-ng-preclinical/src/test/java/org/shanoir/ng/utils/AnimalSubjectModelUtil.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/configuration/amqp/RabbitMQSubjectService.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/model/Subject.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/repository/SubjectRepository.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/service/SubjectService.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/service/SubjectServiceImpl.java
Labels: BUGFIX, REVIEWABLE

#1792 fix date display in tables + underline in datepicker
  shanoir-ng-front/src/app/shared/components/table/table.component.ts
  shanoir-ng-front/src/app/shared/date-picker/date-picker.component.ts
Labels: frontend, BUGFIX
