Repository fli-iam/shanoir-ng, pull requests merged in 2023-06, with the labels that each got.

#1727 [fli-iam#1702] Add more precises messages in import job
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/service/DatasetAcquisitionServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/dto/Study.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/BidsImporterService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/EegImporterService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/ImporterService.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/datasetacquisition/service/ImporterServiceTest.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterApiController.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterManagerService.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dcm2nii/DatasetsCreatorAndNIfTIConverterService.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dcm2nii/SerieToDatasetsSeparator.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/ImagesCreatorAndDicomFileAnalyzerService.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/model/Study.java
Labels: REVIEWABLE

#1716 Column sort bugs
  shanoir-ng-front/src/app/dataset-acquisitions/dataset-acquisition-list/dataset-acquisition-list.component.ts
  shanoir-ng-front/src/app/examinations/examination-list/examination-list.component.ts
Labels: REVIEWABLE

#1756 shanoir-issue#1754: filter subjectStudies for which auth user doesn't have access
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/security/StudySecurityService.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/controler/SubjectApi.java
Labels: BUGFIX, REVIEWABLE

#1715 [fli-iam#1280] Add service-account client on keycloak conf
  docker-compose/keycloak/cfg/shanoir-ng-realm.json
  docker-compose/keycloak/entrypoint
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/carmin/output/DefaultOutputProcessing.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/carmin/schedule/ExecutionStatusMonitor.java
  shanoir-ng-datasets/src/main/resources/application.yml
  shanoir-ng-front/src/app/async-tasks/async-tasks.component.ts
  shanoir-ng-front/src/app/datasets/dataset-processing/dataset-processing.component.html
  shanoir-ng-front/src/app/processing/pipelines/pipeline/pipeline.component.html
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/CarminDataApi.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/CarminDataApiController.java
Labels: security, REVIEWABLE
