Repository fli-iam/shanoir-ng, pull requests merged in 2023-11, with the labels that each got.

#1935 Fix some small issues on dataset view
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetServiceImpl.java
  shanoir-ng-front/src/app/datasets/dataset/common/dataset.common.component.html
  shanoir-ng-front/src/app/datasets/dataset/common/dataset.common.component.ts
  shanoir-ng-front/src/app/datasets/dataset/dataset.component.ts
Labels: REVIEWABLE

#1951 #1950-multi frame download
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/download/WADODownloaderService.java
Labels: backend, Download

#1952 shanoir-issue#1947: fix date format in tables
  shanoir-ng-front/src/app/shared/components/table/table.component.ts
Labels: frontend, REVIEWABLE

#1949 [fli-iam#1948] Add release version tag for docker images
  .github/workflows/docker.yml
Labels: REVIEWABLE

#1865 [fli-iam#1864] Add NIRS type BIDS
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/bids/service/BIDSServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/modality/BidsDataType.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/model/DatasetModalityType.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/security/DatasetSecurityService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetUtils.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/controler/DatasetAcquisitionApi.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/dto/mapper/DatasetAcquisitionDatasetsMapper.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/dto/mapper/DatasetAcquisitionMapper.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/service/DatasetAcquisitionService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/BidsImporterService.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/datasetacquisition/DatasetAcquisitionApiSecurityTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/exporter/service/BidsServiceTest.java
  shanoir-ng-front/src/app/dataset-acquisitions/dataset-acquisition/dataset-acquisition.component.html
  shanoir-ng-front/src/app/dataset-acquisitions/shared/dataset-acquisition.dto.ts
  shanoir-ng-front/src/app/datasets/dataset/common/dataset.common.component.html
  shanoir-ng-front/src/app/datasets/shared/dataset-type.model.ts
  shanoir-ng-front/src/app/enum/bids-data-type.enum.ts
  shanoir-ng-front/src/app/enum/dataset-modality-type.enum.ts
  shanoir-ng-front/src/app/import/bids/bids-upload.component.html
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/bids/BidsImporterApiController.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/manufacturermodel/model/DatasetModalityType.java
Labels: REVIEWABLE

#1966 [CI] Push docker image with version in tag
  .github/workflows/docker.yml
Labels: REVIEWABLE

#1967 [CI] Docker push : change trigger condition
  .github/workflows/docker.yml
Labels: REVIEWABLE

#1946 [Fli iam#1884] Execution monitoring as parent of processing
  docker-compose/database/db-changes/datasets/0036_create_execution_monitoring.sql
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/modality/ProcessedDatasetType.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/dto/DatasetProcessingDTO.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/dto/mapper/DatasetProcessingDecorator.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/dto/mapper/DatasetProcessingMapper.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/model/DatasetProcessing.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/monitoring/model/ExecutionMonitoring.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/monitoring/schedule/ExecutionStatusMonitor.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/resource/ProcessingResourceRepository.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/resource/ProcessingResourceService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/resource/ProcessingResourceServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/resulthandler/DefaultHandler.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/resulthandler/ResultHandlerService.java
  shanoir-ng-front/src/app/app-routing.module.ts
  shanoir-ng-front/src/app/app.module.ts
  shanoir-ng-front/src/app/datasets/dataset-processing/dataset-processing.component.html
  shanoir-ng-front/src/app/datasets/dataset-processing/dataset-processing.component.ts
  shanoir-ng-front/src/app/datasets/dataset/dataset.component.html
  shanoir-ng-front/src/app/datasets/shared/dataset-processing.dto.ts
  shanoir-ng-front/src/app/datasets/shared/dataset-processing.model.ts
  shanoir-ng-front/src/app/datasets/tree/processing-node.component.ts
  shanoir-ng-front/src/app/processing/pipelines/pipelines.component.html
  shanoir-ng-front/src/app/processing/processing.component.css
  shanoir-ng-front/src/app/processing/processing.component.html
  shanoir-ng-front/src/app/processing/processing.component.ts
  shanoir-ng-front/src/app/processing/processing.service.ts
  shanoir-ng-front/src/app/solr/solr.search.component.ts
  shanoir-ng-front/src/app/studies/study/study.component.ts
  shanoir-ng-front/src/app/vip/execution.data-service.spec.ts
  shanoir-ng-front/src/app/vip/execution.data-service.ts
  shanoir-ng-front/src/app/vip/execution/execution.component.css
  shanoir-ng-front/src/app/vip/execution/execution.component.html
  shanoir-ng-front/src/app/vip/execution/execution.component.spec.ts
  shanoir-ng-front/src/app/vip/execution/execution.component.ts
  shanoir-ng-front/src/app/vip/execution/file-entity.ts
  shanoir-ng-front/src/app/vip/pipelines/pipeline/pipeline.component.css
  shanoir-ng-front/src/app/vip/pipelines/pipeline/pipeline.component.html
  shanoir-ng-front/src/app/vip/pipelines/pipeline/pipeline.component.spec.ts
  shanoir-ng-front/src/app/vip/pipelines/pipeline/pipeline.component.ts
  shanoir-ng-front/src/app/vip/pipelines/pipelines.component.css
  shanoir-ng-front/src/app/vip/pipelines/pipelines.component.html
  shanoir-ng-front/src/app/vip/pipelines/pipelines.component.spec.ts
  shanoir-ng-front/src/app/vip/pipelines/pipelines.component.ts
Labels: REVIEWABLE
