Repository fli-iam/shanoir-ng, pull requests merged in 2023-04, with the labels that each got.

#1672 #1667 access request buttons
  shanoir-ng-front/src/app/users/access-request/access-request.component.html
Labels: BUGFIX

#1664 [fli-iam#248-2] add extra files to total size
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/repository/DatasetRepository.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationServiceImpl.java
  shanoir-ng-front/src/app/studies/shared/study.service.ts
  shanoir-ng-front/src/app/studies/study/study.component.html
  shanoir-ng-front/src/app/studies/study/study.component.ts
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/controler/StudyApi.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/controler/StudyApiController.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/service/StudyService.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/service/StudyServiceImpl.java
Labels: feature, REVIEWABLE

#1674 #1668 - invitation as expert bug
  shanoir-ng-front/src/app/studies/studyuser/studyuser-list.component.ts
  shanoir-ng-users/src/main/java/org/shanoir/ng/accessrequest/controller/AccessRequestApi.java
  shanoir-ng-users/src/main/java/org/shanoir/ng/accessrequest/controller/AccessRequestApiController.java
  shanoir-ng-users/src/main/java/org/shanoir/ng/user/service/UserService.java
  shanoir-ng-users/src/main/java/org/shanoir/ng/user/service/UserServiceImpl.java
  shanoir-ng-users/src/test/java/org/shanoir/ng/accessrequest/AccessRequestApiControllerTest.java
Labels: BUGFIX, REVIEWABLE

#1677 #1676 import logs not working anymore
  shanoir-ng-import/src/main/resources/logback-spring.xml
Labels: BUGFIX, REVIEWABLE

#1687 #1685-does-not-contain-study-card
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/model/Operation.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/model/condition/StudyCardCondition.java
  shanoir-ng-front/src/app/study-cards/shared/study-card.model.ts
  shanoir-ng-front/src/app/study-cards/study-card-rules/condition/condition.component.ts
Labels: feature, REVIEWABLE
