Repository fli-iam/shanoir-ng, pull requests merged in 2024-11, with the labels that each got.

#2484 Shanoir issue#2475 subject name
  shanoir-ng-front/src/app/studies/tree/study-node.component.ts
  shanoir-ng-front/src/app/subjects/subject/subject.component.html
  shanoir-ng-front/src/app/subjects/subject/subject.component.ts
  shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/controler/SubjectApiController.java
Labels: REVIEWABLE

#2442 shanoir-issue#2188-2: deletion of exam in async way
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/configuration/amqp/RabbitMQDatasetsService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/controler/DatasetAcquisitionApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/service/DatasetAcquisitionService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/service/DatasetAcquisitionServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/controler/ExaminationApi.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/controler/ExaminationApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/ImporterService.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/datasetacquisition/DatasetAcquisitionServiceSecurityTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/dicom/web/DICOMJsonApiControllerTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/examination/ExaminationApiControllerTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/examination/ExaminationServiceSecurityTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/examination/ExaminationServiceTest.java
  shanoir-ng-front/src/app/shared/components/entity/entity-list.component.abstract.ts
  shanoir-ng-front/src/app/shared/components/entity/entity.abstract.service.ts
  shanoir-ng-front/src/app/shared/side-menu/side-menu.component.html
  shanoir-ng-ms-common/src/main/java/org/shanoir/ng/shared/event/ShanoirEvent.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/configuration/amqp/RabbitMQStudiesService.java
  shanoir-ng-users/src/main/java/org/shanoir/ng/events/ShanoirEventsService.java
  shanoir-ng-users/src/main/java/org/shanoir/ng/tasks/AsyncTaskApiController.java
Labels: frontend, backend, examination, REVIEWABLE

#2450 shanoir-issue#2446: add list of studies of subject on subjectDelete
  shanoir-ng-front/src/app/shared/components/confirm-dialog/confirm-dialog.component.css
  shanoir-ng-front/src/app/shared/components/confirm-dialog/confirm-dialog.component.html
  shanoir-ng-front/src/app/shared/components/entity/entity-list.component.abstract.ts
  shanoir-ng-front/src/app/shared/components/entity/entity.abstract.service.ts
  shanoir-ng-front/src/app/shared/components/entity/entity.component.abstract.ts
  shanoir-ng-front/src/app/subjects/shared/subject.service.ts
  shanoir-ng-front/src/app/subjects/subject-list/subject-list.component.ts
  shanoir-ng-front/src/app/subjects/subject/subject.component.ts
Labels: frontend, REVIEWABLE

#2434 shanoir-issue#2307: solr search detects keywords and switch to expertMode
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/solrj/SolrJWrapperImpl.java
  shanoir-ng-front/src/app/solr/solr.search.component.html
  shanoir-ng-front/src/app/solr/solr.search.component.ts
  shanoir-ng-front/src/app/solr/text-search/solr.text-search-mode.component.ts
  shanoir-ng-front/src/app/solr/text-search/solr.text-search.component.html
  shanoir-ng-front/src/app/solr/text-search/solr.text-search.component.ts
Labels: frontend, REVIEWABLE

#2478 #2476 - create processing error
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/model/Dataset.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/security/DatasetSecurityService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetServiceImpl.java
  shanoir-ng-front/src/app/import/processed-dataset-clinical-context/processed-dataset-clinical-context.component.css
  shanoir-ng-front/src/app/import/processed-dataset-clinical-context/processed-dataset-clinical-context.component.html
  shanoir-ng-front/src/app/import/processed-dataset-clinical-context/processed-dataset-clinical-context.component.ts
Labels: blocking, import, regression, WorkInProgress, Core (roadmap)

#2453 ShUp new profile OFSEP-VHD + fix UTF-8 in DicomDirGenerator
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/DicomDirGeneratorService.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/DicomDirToModelService.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/DicomSerieAndInstanceAnalyzer.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/ImagesCreatorAndDicomFileAnalyzerService.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/SeriesNumberOrDescriptionSorter.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/SeriesNumberSorter.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/query/QueryPACSService.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/model/Instance.java
  shanoir-uploader/READ_ME.txt
  shanoir-uploader/pom.xml
  shanoir-uploader/src/main/java/org/shanoir/uploader/ShUpConfig.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/action/DownloadOrCopyRunnable.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/action/init/InitialStartupState.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/action/init/LoginPanelActionListener.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/dicom/DicomServerClient.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/dicom/query/SerieTreeNode.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/gui/LoginConfigurationPanel.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/utils/ImportUtils.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/utils/Util.java
  shanoir-uploader/src/main/resources/logback.xml
  shanoir-uploader/src/main/resources/messages_en.properties
  shanoir-uploader/src/main/resources/messages_fr.properties
  shanoir-uploader/src/main/resources/profile.OFSEP-VHD-Qualif/keycloak.json
  shanoir-uploader/src/main/resources/profile.OFSEP-VHD-Qualif/profile.properties
  shanoir-uploader/src/main/resources/profile.OFSEP-VHD/keycloak.json
  shanoir-uploader/src/main/resources/profile.OFSEP-VHD/profile.properties
  shanoir-uploader/src/main/resources/profiles.properties
Labels: ShanoirUploader, REVIEWABLE
