Repository fli-iam/shanoir-ng, pull requests merged in 2024-04, with the labels that each got.

#2162 shanoir-issue#2161: fix copy of datasets
  docker-compose/database/db-changes/datasets/0048_add_uniquekey_dataset.sql
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/modality/MrDataset.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/model/Dataset.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetCopyServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/model/mr/MrProtocol.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/model/mr/MrProtocolMetadata.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/model/mr/MrProtocolSCMetadata.java
Labels: bug, backend, REVIEWABLE

#2172 Angular 15 to 17
  shanoir-ng-front/angular.json
  shanoir-ng-front/package-lock.json
  shanoir-ng-front/package.json
  shanoir-ng-front/src/app/shared/components/confirm-dialog/confirm-dialog.service.ts
  shanoir-ng-front/src/app/shared/roles/auth-admin-guard.ts
  shanoir-ng-front/src/app/shared/roles/auth-admin-or-expert-guard.ts
  shanoir-ng-front/src/app/shared/roles/auth-can-import-from-PACS-guard.ts
  shanoir-ng-front/src/app/shared/roles/login-guard.ts
  shanoir-ng-front/src/app/users/account-request/account-request.component.html
  shanoir-ng-front/tsconfig.app.json
  shanoir-ng-front/tsconfig.json
Labels: REVIEWABLE

#2182 filter tasks by user
  shanoir-ng-users/src/main/java/org/shanoir/ng/events/ShanoirEventsService.java
  shanoir-ng-users/src/main/java/org/shanoir/ng/tasks/AsyncTaskApiController.java
  shanoir-ng-users/src/main/java/org/shanoir/ng/tasks/UserSseEmitter.java
Labels: bug, security, critical, BUGFIX, REVIEWABLE

#2085 shanoir-issue#2081: Tag and Quality tab show message + html fixes
  shanoir-ng-front/src/app/quality-control/quality-control.component.html
  shanoir-ng-front/src/app/quality-control/quality-control.component.ts
  shanoir-ng-front/src/app/shared/components/entity/entity.component.abstract.ts
  shanoir-ng-front/src/app/studies/study/study.component.html
  shanoir-ng-front/src/app/tags/tag.creator.component.html
  shanoir-ng-front/src/app/tags/tag.creator.component.ts
Labels: frontend, minor, REVIEWABLE

#2147 subject study on copy + copied datasets ignored by quality check
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/configuration/amqp/RabbitMQDatasetsService.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/configuration/amqp/RabbitMQImportService.java
  shanoir-ng-ms-common/src/main/java/org/shanoir/ng/shared/configuration/RabbitMQConfiguration.java
  shanoir-ng-ms-common/src/main/java/org/shanoir/ng/shared/subjectstudy/SubjectStudyDTO.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/messaging/SubjectStudyUpdateBroadcastService.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/service/RelatedDatasetServiceImpl.java
  shanoir-ng-study-rights/src/main/java/org/shanoir/ng/study/rights/ampq/RabbitMqStudyUserService.java
Labels: bug, backend, REVIEWABLE

#2191 shanoir-issue#2175: add examination.comment to examination-list
  shanoir-ng-front/src/app/examinations/examination-list/examination-list.component.ts
Labels: frontend, examination, REVIEWABLE

#2173 shanoir-issue#2155: improve delete of examination
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/bids/service/BIDSService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/bids/service/BIDSServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/configuration/amqp/RabbitMQDatasetsService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/controler/DatasetAcquisitionApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/service/DatasetAcquisitionServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/WADOURLHandler.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/service/DICOMWebService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/controler/ExaminationApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationServiceImpl.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/dataset/DatasetApiControllerTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/datasetacquisition/DatasetAcquisitionApiControllerTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/examination/ExaminationApiControllerTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/examination/ExaminationServiceTest.java
  shanoir-ng-front/src/app/dataset-acquisitions/dataset-acquisition-list/dataset-acquisition-list.component.ts
  shanoir-ng-ms-common/src/main/java/org/shanoir/ng/shared/configuration/RabbitMQConfiguration.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/controler/SubjectApiController.java
Labels: backend, datasets, performance, REVIEWABLE
