Repository fli-iam/shanoir-ng, pull requests merged in 2024-07, with the labels that each got.

#2294 #2293-updated-exam-bug
  docker-compose/database/db-changes/datasets/0050_examination_update_bug
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationServiceImpl.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/examination/ExaminationServiceTest.java
Labels: BUGFIX, REVIEWABLE

#2282 shanoir-issue#2240: rename 'acquisition equipment' to 'center equipment'
  shanoir-ng-front/src/app/acquisition-equipments/acquisition-equipment-list/acquisition-equipment-list.component.html
  shanoir-ng-front/src/app/acquisition-equipments/acquisition-equipment-list/acquisition-equipment-list.component.ts
  shanoir-ng-front/src/app/acquisition-equipments/acquisition-equipment/acquisition-equipment.component.html
  shanoir-ng-front/src/app/centers/center-list/center-list.component.html
  shanoir-ng-front/src/app/centers/center/center.component.html
  shanoir-ng-front/src/app/coils/coil-list/coil-list.component.ts
  shanoir-ng-front/src/app/coils/coil/coil.component.html
  shanoir-ng-front/src/app/coils/coil/coil.component.ts
  shanoir-ng-front/src/app/dataset-acquisitions/dataset-acquisition-list/dataset-acquisition-list.component.ts
  shanoir-ng-front/src/app/dataset-acquisitions/dataset-acquisition/dataset-acquisition.component.html
  shanoir-ng-front/src/app/examinations/examination-list/examination-list.component.ts
  shanoir-ng-front/src/app/import/bids/bids-upload.component.html
  shanoir-ng-front/src/app/import/clinical-context/clinical-context.component.html
  shanoir-ng-front/src/app/import/eeg-clinical-context/eeg-clinical-context.component.html
  shanoir-ng-front/src/app/preclinical/examination/list/animal-examination-list.component.ts
  shanoir-ng-front/src/app/shared/side-menu/side-menu.component.html
  shanoir-ng-front/src/app/solr/solr.search.component.html
  shanoir-ng-front/src/app/solr/solr.search.component.ts
  shanoir-ng-front/src/app/studies/study/study.component.html
  shanoir-ng-front/src/app/study-cards/apply-study-card-on/apply-study-card-on.component.ts
  shanoir-ng-front/src/app/study-cards/study-card-list/study-card-list-for-rules.component.ts
  shanoir-ng-front/src/app/study-cards/study-card-list/study-card-list.component.ts
  shanoir-ng-front/src/app/study-cards/study-card/study-card.component.html
Labels: frontend, ROADMAP, REVIEWABLE

#2283 shanoir-issue#2224: rename solr column + new column with da.importDate
  docker-compose/database/db-changes/datasets/0050_rename_creationDate_importDate.sql
  docker-compose/solr/core/schema.xml
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/dto/DatasetAcquisitionDTO.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/model/DatasetAcquisition.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/dto/ImportJob.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/BidsImporterService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/EegImporterService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/strategies/datasetacquisition/CtDatasetAcquisitionStrategy.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/strategies/datasetacquisition/MrDatasetAcquisitionStrategy.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/strategies/datasetacquisition/PetDatasetAcquisitionStrategy.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/strategies/datasetacquisition/XaDatasetAcquisitionStrategy.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/model/ShanoirMetadata.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/model/ShanoirSolrDocument.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/model/ShanoirSolrQuery.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/repository/ShanoirMetadataRepositoryImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/service/SolrServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/solrj/SolrJWrapperImpl.java
  shanoir-ng-front/src/app/dataset-acquisitions/dataset-acquisition/dataset-acquisition.component.html
  shanoir-ng-front/src/app/dataset-acquisitions/shared/dataset-acquisition.dto.ts
  shanoir-ng-front/src/app/dataset-acquisitions/shared/dataset-acquisition.model.ts
  shanoir-ng-front/src/app/solr/solr.document.model.ts
  shanoir-ng-front/src/app/solr/solr.search.component.ts
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterApiController.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterManagerService.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/bids/BidsImporterApiController.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/model/ImportJob.java
Labels: backend, solr, REVIEWABLE

#2330 #2326-re-apply-study-card
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/download/WADODownloaderService.java
Labels: BUGFIX, REVIEWABLE

#2336 Shanoir issue#2284: solr filter importDate
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/model/ShanoirSolrQuery.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/solrj/SolrJWrapperImpl.java
  shanoir-ng-front/src/app/solr/solr.document.model.ts
  shanoir-ng-front/src/app/solr/solr.search.component.html
  shanoir-ng-front/src/app/solr/solr.search.component.ts
  shanoir-ng-front/src/app/solr/text-search/solr.text-search-mode.component.html
Labels: solr, REVIEWABLE

#2339 shanoir-issue#2284-2: fix issue with exam date
  shanoir-ng-front/src/app/solr/solr.search.component.ts
Labels: frontend, REVIEWABLE
