Repository fli-iam/shanoir-ng, pull requests merged in 2024-08, with the labels that each got.

#2353 Fix for GitHub issue #2345
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/DicomPersisterService.java
Labels: REVIEWABLE

#2349 shanoir-issue#2346: show study card selection on brucker import
  shanoir-ng-front/src/app/import/pre-clinical-context/pre-clinical-context.component.ts
Labels: frontend, import, preclinical

#2356 shanoir-issue#2355: do not re-route users to /home
  shanoir-ng-front/src/app/shared/roles/auth-admin-or-expert-guard.ts
Labels: frontend, REVIEWABLE

#2358 shanoir-issue#2334: add console html component in keycloak page to display error
  docker-compose/keycloak/themes/shanoir-theme/login/messages/messages_en.properties
  shanoir-ng-front/src/app/users/account-request/account-request.component.css
  shanoir-ng-front/src/app/users/account-request/account-request.component.html
  shanoir-ng-front/src/app/users/account-request/account-request.component.ts
Labels: frontend, css, REVIEWABLE

#2351 shanoir-issue#2350: OHIF - fix issues
  docker-compose/Dockerfile
  docker-compose/nginx/viewer/app-config.js
  shanoir-ng-front/src/app/examinations/tree/examination-node.component.ts
Labels: WorkInProgress

#2365 Add download options : folder structure
  shanoir-ng-front/src/app/shared/mass-download/download-setup/download-setup.component.css
  shanoir-ng-front/src/app/shared/mass-download/download-setup/download-setup.component.html
  shanoir-ng-front/src/app/shared/mass-download/download-setup/download-setup.component.ts
  shanoir-ng-front/src/app/shared/mass-download/mass-download.service.ts
Labels: frontend, user priority, Download

#2367 shanoir-issue#2366: special char in ohif
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/service/DICOMWebService.java
Labels: backend, REVIEWABLE, OHIF

#2362 ShUp: optimize download from pacs + upload to server
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/query/QueryPACSService.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/model/Serie.java
  shanoir-uploader/READ_ME.txt
  shanoir-uploader/src/main/java/org/shanoir/uploader/ShUpConfig.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/action/DownloadOrCopyActionListener.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/action/DownloadOrCopyRunnable.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportFromTableRunner.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/action/RSDocumentListener.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/action/SelectionActionListener.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/dicom/DicomServerClient.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/dicom/IDicomServerClient.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/gui/CurrentUploadsWindowTable.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/gui/ImportFromTableWindow.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/gui/MainWindow.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/upload/UploadServiceJob.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/utils/ImportUtils.java
  shanoir-uploader/src/main/resources/messages_en.properties
  shanoir-uploader/src/main/resources/messages_fr.properties
Labels: REVIEWABLE

#2340 shanoir-issue#2333: show full content of cell on mouse over
  shanoir-ng-front/src/app/shared/components/table/table.component.html
Labels: frontend, REVIEWABLE

#2376 shanoir-issue#2375: special char in ohif study list
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/service/DICOMWebService.java
Labels: REVIEWABLE, OHIF

#2370 Index MeasurementDataset to Solr + fix for bootstrap.sh
  bootstrap.sh
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/modality/MrDataset.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/StowRSMultipartRelatedRequestFilter.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/DicomSEGAndSRImporterService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/ImporterService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/repository/ShanoirMetadataRepositoryImpl.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/dataset/DatasetApiControllerTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/dataset/DatasetDownloaderServiceTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/datasetacquisition/DatasetAcquisitionApiControllerTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/dicom/web/DICOMJsonApiControllerTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/examination/ExaminationApiControllerTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/exporter/controller/BidsApiControllerTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/studycard/StudyCardApiControllerTest.java
Labels: REVIEWABLE

#2379 shanoir-issue#2378: add button to open ohif in seg mode
  shanoir-ng-front/src/app/examinations/examination/examination.component.html
  shanoir-ng-front/src/app/examinations/examination/examination.component.ts
Labels: REVIEWABLE, OHIF
