Repository fli-iam/shanoir-ng, pull requests merged in 2024-09, with the labels that each got.

#2291 shanoir-issue#2248: study's history
  docker-compose/database/db-changes/users/0005_create_study_user_tables.sql
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/configuration/amqp/RabbitMQDatasetsService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/service/DatasetAcquisitionServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/controler/ExaminationApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/EegImporterService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/ImporterService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/service/CardsProcessingService.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/examination/ExaminationApiControllerTest.java
  shanoir-ng-front/src/app/app.module.ts
  shanoir-ng-front/src/app/shared/components/entity/entity.component.abstract.ts
  shanoir-ng-front/src/app/studies/study-history/study-history.component.css
  shanoir-ng-front/src/app/studies/study-history/study-history.component.html
  shanoir-ng-front/src/app/studies/study-history/study-history.component.ts
  shanoir-ng-front/src/app/studies/study/study.component.html
  shanoir-ng-front/src/app/studies/study/study.component.ts
  shanoir-ng-front/src/app/users/shanoir-event/shanoir-event.model.ts
  shanoir-ng-front/src/app/users/shanoir-event/shanoir-event.service.ts
  shanoir-ng-front/src/app/utils/app.utils.ts
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterManagerService.java
  shanoir-ng-ms-common/src/main/java/org/shanoir/ng/shared/event/ShanoirEvent.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/configuration/amqp/RabbitMQStudiesService.java
  shanoir-ng-users/pom.xml
  shanoir-ng-users/src/main/java/org/shanoir/ng/ShanoirUsersManagement.java
  shanoir-ng-users/src/main/java/org/shanoir/ng/accessrequest/controller/AccessRequestApiController.java
  shanoir-ng-users/src/main/java/org/shanoir/ng/configuration/amqp/RabbitMQUserService.java
  shanoir-ng-users/src/main/java/org/shanoir/ng/events/EventsApi.java
  shanoir-ng-users/src/main/java/org/shanoir/ng/events/EventsApiController.java
  shanoir-ng-users/src/main/java/org/shanoir/ng/events/ShanoirEventLight.java
  shanoir-ng-users/src/main/java/org/shanoir/ng/events/ShanoirEventRepository.java
  shanoir-ng-users/src/main/java/org/shanoir/ng/events/ShanoirEventRepositoryCustom.java
  shanoir-ng-users/src/main/java/org/shanoir/ng/events/ShanoirEventRepositoryImpl.java
  shanoir-ng-users/src/main/java/org/shanoir/ng/events/ShanoirEventsService.java
  shanoir-ng-users/src/main/java/org/shanoir/ng/user/repository/UserRepository.java
  shanoir-ng-users/src/test/java/org/shanoir/ng/accessrequest/AccessRequestApiControllerTest.java
Labels: frontend, backend, study, REVIEWABLE

#2383 shanoir-issue#2368-2: checkboxes + open multiple exams in ohif viewer
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/DICOMWebApi.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/DICOMWebApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/SeriesInstanceUIDHandler.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/StudyInstanceUIDHandler.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/service/DICOMWebService.java
  shanoir-ng-front/src/app/dataset-acquisitions/dataset-acquisition/dataset-acquisition.component.html
  shanoir-ng-front/src/app/dataset-acquisitions/tree/dataset-acquisition-node.component.html
  shanoir-ng-front/src/app/examinations/tree/examination-node.component.html
  shanoir-ng-front/src/app/examinations/tree/examination-node.component.ts
  shanoir-ng-front/src/app/solr/solr.search.component.ts
  shanoir-ng-front/src/app/studies/study/study-tree.component.html
  shanoir-ng-front/src/app/studies/study/study-tree.component.ts
  shanoir-ng-front/src/app/tree/tree.model.ts
Labels: frontend, OHIF

#2391 shanoir-issue#2389: allow 'view dicom' with exams or acquisition from one exam
  shanoir-ng-front/src/app/examinations/examination/examination.component.html
  shanoir-ng-front/src/app/studies/study/study-tree.component.html
  shanoir-ng-front/src/app/studies/study/study-tree.component.ts
  shanoir-ng-front/src/app/tree/tree.model.ts
Labels: frontend, REVIEWABLE, OHIF

#2384 export table as csv
  shanoir-ng-front/src/app/shared/components/table/table.component.css
  shanoir-ng-front/src/app/shared/components/table/table.component.html
  shanoir-ng-front/src/app/shared/components/table/table.component.ts
  shanoir-ng-front/src/app/studies/study/study.component.css
  shanoir-ng-front/src/app/study-cards/quality-card/quality-card.component.ts
Labels: frontend, feature, user priority

#2401 shanoir-issue#2397: remove 'download study' button
  shanoir-ng-front/src/app/shared/mass-download/mass-download.service.ts
  shanoir-ng-front/src/app/studies/study/study.component.html
  shanoir-ng-front/src/app/studies/study/study.component.ts
Labels: frontend, REVIEWABLE
