Repository fli-iam/shanoir-ng, pull requests merged in 2024-03, with the labels that each got.

#2047 Shanoir issue#2023 and #2030: download file is available before making sure the upload is done
  shanoir-ng-front/src/app/examinations/examination/examination.component.html
  shanoir-ng-front/src/app/examinations/examination/examination.component.ts
  shanoir-ng-front/src/app/shared/components/entity/entity.component.abstract.ts
  shanoir-ng-front/src/app/studies/study/study.component.ts
Labels: frontend, REVIEWABLE

#2109 shanoir-issue#2096: add a 'jump to page' feature
  shanoir-ng-front/src/app/shared/components/table/pager/pager.component.html
  shanoir-ng-front/src/app/shared/components/table/table.component.css
  shanoir-ng-front/src/app/shared/components/table/table.component.html
  shanoir-ng-front/src/app/shared/components/table/table.component.ts
Labels: frontend, REVIEWABLE

#2076 #2068 keycloak upgrade
  docker-compose/keycloak/Dockerfile
  docker-compose/keycloak/entrypoint
  shanoir-ng-back/pom.xml
  shanoir-ng-front/src/app/shared/keycloak/keycloak.service.ts
  shanoir-ng-keycloak-auth/pom.xml
  shanoir-uploader/pom.xml
Labels: REVIEWABLE

#2062 [Fli iam#2059] Use new backend execution & pipeline APIs in Shanoir front
  shanoir-ng-datasets/pom.xml
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/download/WADODownloaderService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/dto/ParameterResourceDTO.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/controller/ExecutionApi.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/controller/ExecutionApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/controller/ExecutionDataApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/controller/PathApi.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/controller/PathApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/controller/PipelineApi.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/controller/PipelineApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/controller/VipClientService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/dto/DatasetParameterDTO.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/dto/ExecutionCandidateDTO.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/dto/ExecutionMonitoringDTO.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/dto/VipExecutionDTO.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/monitoring/controller/ExecutionMonitoringApi.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/monitoring/controller/ExecutionMonitoringApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/monitoring/model/ExecutionDTO.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/monitoring/schedule/ExecutionStatusMonitorService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/monitoring/service/ExecutionMonitoringService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/monitoring/service/ExecutionMonitoringServiceImpl.java
  shanoir-ng-datasets/src/main/resources/application.yml
  shanoir-ng-datasets/src/main/resources/logback-spring.xml
  shanoir-ng-front/src/app/app.module.ts
  shanoir-ng-front/src/app/datasets/dataset-processing/dataset-processing.component.ts
  shanoir-ng-front/src/app/home/home.component.html
  shanoir-ng-front/src/app/shared/keycloak/keycloak.service.ts
  shanoir-ng-front/src/app/utils/app.utils.ts
  shanoir-ng-front/src/app/vip/execution-monitorings/execution-monitoring.service.ts
  shanoir-ng-front/src/app/vip/execution-monitorings/execution-monitorings.component.ts
  shanoir-ng-front/src/app/vip/execution/execution.component.ts
  shanoir-ng-front/src/app/vip/execution/execution.service.ts
  shanoir-ng-front/src/app/vip/models/dataset-parameter.dto.ts
  shanoir-ng-front/src/app/vip/models/descriptor.ts
  shanoir-ng-front/src/app/vip/models/descriptorAssertions.ts
  shanoir-ng-front/src/app/vip/models/descriptorAssertionsOutputfiles.ts
  shanoir-ng-front/src/app/vip/models/descriptorEnvironmentvariables.ts
  shanoir-ng-front/src/app/vip/models/descriptorErrorcodes.ts
  shanoir-ng-front/src/app/vip/models/descriptorGroups.ts
  shanoir-ng-front/src/app/vip/models/descriptorInputs.ts
  shanoir-ng-front/src/app/vip/models/descriptorOutputfiles.ts
  shanoir-ng-front/src/app/vip/models/descriptorSuggestedresources.ts
  shanoir-ng-front/src/app/vip/models/descriptorTests.ts
  shanoir-ng-front/src/app/vip/models/execution-candidate.dto.ts
  shanoir-ng-front/src/app/vip/models/execution-monitoring.model.ts
  shanoir-ng-front/src/app/vip/models/execution.ts
  shanoir-ng-front/src/app/vip/models/path.ts
  shanoir-ng-front/src/app/vip/models/pipeline.ts
  shanoir-ng-front/src/app/vip/models/platformProperties.ts
  shanoir-ng-front/src/app/vip/pipelines/pipeline/pipeline.service.ts
  shanoir-ng-front/src/app/vip/pipelines/pipelines.component.ts
  shanoir-ng-front/src/app/vip/shared/vip-client.service.ts
  shanoir-ng-ms-common/src/main/java/org/shanoir/ng/shared/controller/GlobalExceptionHandler.java
Labels: WorkInProgress

#2092 [Fli iam#2082] Add fields to the OFSEP stats export
  docker-compose/database/3_add_statistics_procedure.sql
  docker-compose/database/db-changes/datasets/46_update_statistics_procedure.sql
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/resulthandler/OFSEPSeqIdHandler.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/processing/resulthandler/output/OFSEPSeqIdProcessingTest.java
Labels: REVIEWABLE

#2111 [fli-iam#2095] Delete linked properties before deleting dataset
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApi.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/repository/DatasetRepository.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/ProcessedDatasetService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/ProcessedDatasetServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/controler/DatasetProcessingApi.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/controler/DatasetProcessingApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/repository/DatasetProcessingRepository.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/service/DatasetProcessingService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/service/DatasetProcessingServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/property/repository/DatasetPropertyRepository.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/property/service/DatasetPropertyService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/property/service/DatasetPropertyServiceImpl.java
Labels: REVIEWABLE

#2116 shanoir-issue#2078: add a check if user isnt part on any study
  shanoir-ng-front/src/app/studies/study-list/study-list.component.ts
Labels: bug, frontend, study
