Repository fli-iam/shanoir-ng, pull requests merged in 2024-06, with the labels that each got.

#2234 2233-processed-dataset-creation - Avoid NPE while creating processed dataset
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetServiceImpl.java
Labels: REVIEWABLE

#2206 [fli-iam#2194] Generate Tags from "organ" dataset properties
  docker-compose/database/db-changes/datasets/0049_create_tables_tags.sql
  docker-compose/database/oneshot-updates/tag_ofsep_organs.sql
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/configuration/amqp/RabbitMQDatasetsService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApi.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/dto/DatasetDTO.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/dto/mapper/DatasetMapper.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/model/Dataset.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/repository/DatasetRepository.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/shared/model/Study.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/shared/model/SubjectStudy.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/shared/model/SubjectStudyDTO.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/shared/service/StudyService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/shared/service/StudyServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/controler/SolrApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/repository/ShanoirMetadataRepositoryCustom.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/repository/ShanoirMetadataRepositoryImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/service/SolrService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/service/SolrServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/tag/mapper/StudyTagMapper.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/tag/model/StudyTag.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/tag/model/StudyTagDTO.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/tag/model/Tag.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/tag/repository/StudyTagRepository.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/tag/service/StudyTagService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/resulthandler/OFSEPSeqIdHandler.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/dataset/DatasetApiControllerTest.java
  shanoir-ng-front/src/app/async-tasks/task.model.ts
  shanoir-ng-front/src/app/dataset-acquisitions/tree/dataset-acquisition-node.component.ts
  shanoir-ng-front/src/app/datasets/shared/dataset.dto.ts
  shanoir-ng-front/src/app/datasets/shared/dataset.model.ts
  shanoir-ng-front/src/app/datasets/tree/dataset-node.component.html
  shanoir-ng-front/src/app/examinations/tree/examination-node.component.ts
  shanoir-ng-front/src/app/shared/components/tree/tree-node.component.html
  shanoir-ng-front/src/app/shared/components/tree/tree-node.component.ts
  shanoir-ng-front/src/app/shared/side-menu/side-menu.component.html
  shanoir-ng-front/src/app/solr/solr.service.ts
  shanoir-ng-front/src/app/studies/study/study.component.ts
  shanoir-ng-front/src/app/studies/tree/reverse-study-node.component.ts
  shanoir-ng-front/src/app/subjects/tree/subject-node.component.ts
  shanoir-ng-front/src/app/tree/tree.model.ts
  shanoir-ng-ms-common/src/main/java/org/shanoir/ng/shared/core/repository/ReadOnlyRepository.java
  shanoir-ng-ms-common/src/main/java/org/shanoir/ng/shared/event/ShanoirEventService.java
  shanoir-ng-ms-common/src/main/java/org/shanoir/ng/shared/event/ShanoirEventType.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/controler/StudyApi.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/controler/StudyApiController.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/dto/StudyDTO.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/security/StudySecurityService.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/service/StudyService.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/service/StudyServiceImpl.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/tag/model/StudyTagDecorator.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/tag/model/StudyTagMapper.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/tag/repository/StudyTagRepository.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/tag/service/StudyTagService.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/tag/service/StudyTagServiceImpl.java
  shanoir-ng-studies/src/test/java/org/shanoir/ng/study/StudyApiControllerTest.java
  shanoir-ng-studies/src/test/java/org/shanoir/ng/study/service/StudyServiceTest.java
  shanoir-ng-users/src/main/java/org/shanoir/ng/events/ShanoirEventsService.java
  shanoir-ng-users/src/main/java/org/shanoir/ng/tasks/AsyncTaskApiController.java
Labels: REVIEWABLE

#2277 shanoir-issue#2274: remove field
  shanoir-ng-front/src/app/studies/study/study.component.html
Labels: frontend, REVIEWABLE

#2269 #2268-bugfix-processing-deletion
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetDownloaderServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/dto/DatasetProcessingDTO.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/dto/mapper/DatasetProcessingDecorator.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/service/DatasetProcessingService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/service/DatasetProcessingServiceImpl.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/dataset/DatasetServiceSecurityTest.java
  shanoir-ng-front/src/app/shared/mass-download/mass-download.service.ts
Labels: bug, REVIEWABLE

#2261 #2256-missing-mr-sequence-variant
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/model/mr/MrSequenceVariant.java
Labels: REVIEWABLE

#2280 Subjects not copied during copy of preclinical datasets
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/configuration/amqp/RabbitMQDatasetsService.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/messaging/SubjectStudyUpdateBroadcastService.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/controler/StudyApiController.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/service/RelatedDatasetServiceImpl.java
Labels: bug, backend, REVIEWABLE
