Repository fli-iam/shanoir-ng, pull requests merged in 2025-04, with the labels that each got.

#2766 #2765 : update keycloack realm for VIP migration
  docker-compose/keycloak/cfg/shanoir-ng-realm.json
Labels: REVIEWABLE, VIP, Maintenance (roadmap)

#2735 shanoir-issue#2734: log error on exam delete
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationServiceImpl.java
Labels: REVIEWABLE

#2755 2753 : some VIP changes
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/ImporterService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/output/handler/DefaultHandler.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/output/handler/OFSEPSeqIdHandler.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/output/service/OutputService.java
  shanoir-ng-front/src/app/datasets/dataset-processing/dataset-processing.component.html
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/vip/controler/ExecutionResultApiController.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/vip/model/GetPathResponse.java
Labels: REVIEWABLE, VIP, next-release

#2715 shanoir-issue#2705: fix delete acq equipment + show logs in service
  shanoir-ng-studies/src/main/java/org/shanoir/ng/acquisitionequipment/repository/AcquisitionEquipmentRepository.java
  shanoir-ng-studies/src/main/resources/logback-spring.xml
Labels: REVIEWABLE

#2718 2717 : Modification of Shanoir prefix for VIP API HTTP requests/responses
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/execution/service/ExecutionServiceImpl.java
  shanoir-ng-datasets/src/main/resources/application.yml
Labels: REVIEWABLE, VIP

#2779 add transactional
  shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/controler/SubjectApiController.java
Labels: next-release

#2709 shanoir-issue#2703: use Long instead of long
  shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/subjects/dto/SubjectDto.java
Labels: REVIEWABLE

#2456 Study card policy
  docker-compose/database/db-changes/studies/0023_update_studycardpolicy.sql
  shanoir-ng-front/src/app/import/clinical-context/clinical-context.abstract.component.ts
  shanoir-ng-front/src/app/studies/study/study.component.html
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/controler/StudyApiController.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/model/StudyCardPolicy.java
Labels: frontend, REVIEWABLE
