Repository fli-iam/shanoir-ng, pull requests merged in 2025-05, with the labels that each got.

#2801 keycloak v26.1.5
  docker-compose/Dockerfile
  docker-compose/keycloak/entrypoint
  shanoir-ng-back/pom.xml
  shanoir-ng-front/package-lock.json
  shanoir-ng-front/package.json
  shanoir-ng-front/src/app/shared/keycloak/keycloak.service.ts
  shanoir-ng-front/src/assets/css/login.css
  shanoir-ng-front/src/index.html
  shanoir-ng-front/tsconfig.json
  shanoir-ng-keycloak-auth/pom.xml
  shanoir-ng-users/src/main/java/org/shanoir/ng/ShanoirUsersManagement.java
  shanoir-uploader/pom.xml
Labels: REVIEWABLE, priority

#2664 2661 : Message instead of stacktrace when requesting VIP pipelines API with no rights
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/pipeline/service/PipelineServiceImpl.java
Labels: REVIEWABLE, VIP

#2827 bugfix compatible study and study card not selected by default
  shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportDialogOpener.java
Labels: ShanoirUploader

#2773 Laurent issue#1735 shup dicom push
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/ImagesCreatorAndDicomFileAnalyzerService.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/model/ImportJob.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/ShUpConfig.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/action/DeleteDirectory.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/action/DownloadOrCopyActionListener.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/action/DownloadOrCopyRunnable.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/action/FindDicomActionListener.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/action/init/ReadyState.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/dicom/DicomServerClient.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/dicom/retrieve/DcmRcvManager.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/gui/CurrentUploadsWindowTable.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/gui/MainWindow.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/model/rest/ManufacturerModel.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/nominativeData/CurrentNominativeDataController.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/nominativeData/DicomPushServiceJob.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/utils/FileUtil.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/utils/ImportUtils.java
Labels: ShanoirUploader

#2819 allow filtering of studies with first letters of the name
  shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportStudyAndStudyCardCBItemListener.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportSubjectNameDocumentFilter.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/gui/ImportDialog.java
  shanoir-uploader/src/main/resources/messages_en.properties
  shanoir-uploader/src/main/resources/messages_fr.properties
Labels: ShanoirUploader

#2851 shanoir-issue#2844-2: prevent users from removing a subject from study edit
  shanoir-ng-front/src/app/shared/components/entity/entity-list.component.abstract.ts
  shanoir-ng-front/src/app/shared/components/subject-study-list/subject-study-list.component.ts
  shanoir-ng-front/src/app/studies/study/study.component.html
  shanoir-ng-front/src/app/subjects/subject/subject.component.html
  shanoir-ng-front/src/app/subjects/subject/subject.component.ts
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/service/StudyServiceImpl.java
Labels: REVIEWABLE
