Repository fli-iam/shanoir-ng, pull requests merged in 2025-08, with the labels that each got.

#2950 #2949 : date according to browser language refracto
  shanoir-ng-front/src/app/app.module.ts
  shanoir-ng-front/src/app/async-tasks/status/task-status.component.html
  shanoir-ng-front/src/app/async-tasks/status/task-status.component.ts
  shanoir-ng-front/src/app/dataset-acquisitions/dataset-acquisition/dataset-acquisition.component.html
  shanoir-ng-front/src/app/dataset-acquisitions/dataset-acquisition/dataset-acquisition.component.ts
  shanoir-ng-front/src/app/datasets/dataset-processing/dataset-processing.component.html
  shanoir-ng-front/src/app/datasets/dataset-processing/dataset-processing.component.ts
  shanoir-ng-front/src/app/datasets/dataset/common/dataset.common.component.html
  shanoir-ng-front/src/app/examinations/examination/examination.component.html
  shanoir-ng-front/src/app/examinations/examination/examination.component.ts
  shanoir-ng-front/src/app/import/select-series/select-series.component.html
  shanoir-ng-front/src/app/import/select-series/select-series.component.ts
  shanoir-ng-front/src/app/preclinical/examination/edit/animal-examination-form.component.html
  shanoir-ng-front/src/app/preclinical/examination/edit/animal-examination-form.component.ts
  shanoir-ng-front/src/app/preclinical/importBruker/select-series/bruker-select-series.component.html
  shanoir-ng-front/src/app/preclinical/importBruker/select-series/bruker-select-series.component.ts
  shanoir-ng-front/src/app/preclinical/pathologies/subjectPathology/edit/subjectPathology-form.component.html
  shanoir-ng-front/src/app/preclinical/pathologies/subjectPathology/edit/subjectPathology-form.component.ts
  shanoir-ng-front/src/app/preclinical/therapies/subjectTherapy/edit/subjectTherapy-form.component.html
  shanoir-ng-front/src/app/preclinical/therapies/subjectTherapy/edit/subjectTherapy-form.component.ts
  shanoir-ng-front/src/app/shared/localLanguage/localDate.abstract.ts
  shanoir-ng-front/src/app/shared/localLanguage/localDateFormat.pipe.ts
  shanoir-ng-front/src/app/solr/solr.search.component.html
  shanoir-ng-front/src/app/solr/solr.search.component.ts
  shanoir-ng-front/src/app/studies/study/study.component.html
  shanoir-ng-front/src/app/studies/study/study.component.ts
  shanoir-ng-front/src/app/subjects/subject/subject.component.html
  shanoir-ng-front/src/app/subjects/subject/subject.component.ts
  shanoir-ng-front/src/app/users/user/user.component.html
  shanoir-ng-front/src/app/users/user/user.component.ts
  shanoir-ng-front/src/main.ts
Labels: frontend, REVIEWABLE

#2808 No tree by default for viewing users
  shanoir-ng-front/src/app/app.component.ts
  shanoir-ng-front/src/app/shared/components/entity/entity.component.abstract.ts
  shanoir-ng-front/src/app/studies/study/tree.service.ts
  shanoir-ng-front/src/app/users/user/user.component.ts
Labels: feature

#2905 #2904 : shanoirId added for VIP download API
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetDownloaderServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/path/PathApiController.java
Labels: Download, REVIEWABLE, VIP

#2967 Single-study subject: ShUp: SubjectStudy removed + StudySecurityService adapted for subject.study
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/shared/repository/AcquisitionEquipmentRepository.java
  shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/subjects/controller/AnimalSubjectApiController.java
  shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/subjects/dto/SubjectDto.java
  shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/subjects/dto/TagDto.java
  shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/subjects/service/AnimalSubjectService.java
  shanoir-ng-preclinical/src/main/java/org/shanoir/ng/preclinical/subjects/service/AnimalSubjectServiceImpl.java
  shanoir-ng-preclinical/src/test/java/org/shanoir/ng/preclinical/subjects/AnimalSubjectApiControllerTest.java
  shanoir-ng-preclinical/src/test/java/org/shanoir/ng/utils/AnimalSubjectModelUtil.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/center/repository/CenterRepository.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/center/service/CenterServiceImpl.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/configuration/amqp/RabbitMQSubjectService.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/security/StudySecurityService.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/controler/SubjectApi.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/model/Subject.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/repository/SubjectRepository.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/subject/service/SubjectService.java
  shanoir-ng-studies/src/test/java/org/shanoir/ng/center/CenterRepositoryTest.java
  shanoir-ng-studies/src/test/java/org/shanoir/ng/study/SubjectStudyApiSecurityTest.java
  shanoir-ng-studies/src/test/java/org/shanoir/ng/subject/SubjectApiSecurityTest.java
  shanoir-ng-studies/src/test/java/org/shanoir/ng/subject/service/SubjectServiceSecurityTest.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportFinishActionListener.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportFromTableRunner.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportStudyAndStudyCardCBItemListener.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportSubjectNameDocumentFilter.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/gui/ImportDialog.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/model/rest/Subject.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/model/rest/SubjectStudy.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/service/rest/ShanoirUploaderServiceClient.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/utils/ImportUtils.java
  shanoir-uploader/src/main/resources/messages_en.properties
  shanoir-uploader/src/main/resources/messages_fr.properties
  shanoir-uploader/src/test/java/org/shanoir/uploader/test/importer/ZipFileImportTest.java
Labels: subject, import, ShanoirUploader, Core (roadmap)

#2856 shanoir-issue#2843: multi-exam import studycard policy
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/ImporterService.java
  shanoir-ng-front/src/app/import/dicom-upload/dicom-upload.component.html
  shanoir-ng-front/src/app/import/dicom-upload/dicom-upload.component.ts
  shanoir-ng-front/src/app/import/shared/dicom-data.model.ts
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterApi.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterApiController.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/model/ImportJob.java
Labels: REVIEWABLE
