Repository fli-iam/shanoir-ng, pull requests merged in 2025-01, with the labels that each got.

#2554 RabbitMQ_missing_queue: Adding rabbitMQ listener method for animal subject deletion in preclinical ms
  shanoir-ng-ms-common/src/main/java/org/shanoir/ng/shared/configuration/RabbitMQConfiguration.java
Labels: REVIEWABLE

#2549 shanoir-issue#2539: use getType instead of instanceof to check modality
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/validation/DatasetsModalityTypeCheckValidator.java
  shanoir-ng-ms-common/src/main/java/org/shanoir/ng/shared/configuration/RabbitMQConfiguration.java
Labels: REVIEWABLE

#2480 Shanoir issue#2463 Delete subject does not appear in study's history
  shanoir-ng-ms-common/src/main/java/org/shanoir/ng/shared/event/ShanoirEventType.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/service/StudyServiceImpl.java
Labels: subject, backend, REVIEWABLE

#2548 #2547 : splitting Solr indexation in multiple transactions
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/service/SolrServiceImpl.java
Labels: REVIEWABLE

#2545 #2544 : Solr processed column value querying modified for being more accurate
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/repository/ShanoirMetadataRepositoryImpl.java
Labels: REVIEWABLE

#2532 #1874 : import job working properly with eeg (logged as jobs)
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/EegImporterService.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterApiController.java
  shanoir-ng-import/src/test/java/org/shanoir/ng/importer/ImporterApiControllerTest.java
Labels: REVIEWABLE

#2535 #2527 : Springboot 3.2.2 -> 3.4.0
  shanoir-ng-back/pom.xml
Labels: REVIEWABLE

#2581 2547 : back to initial transaction state (not splitted transaction)
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/service/SolrServiceImpl.java
Labels: REVIEWABLE

#2522 shanoir-issue#2513: remove monoCenter
  docker-compose/database/db-changes/studies/0022_drop_monocenter.sql
  docker-compose/migration/init/2_studies_tables.sql
  docker-compose/migration/neurinfo/v1/2_studies_migration.py
  docker-compose/migration/neurinfo/v1/2_studies_tables.sql
  docker-compose/migration/neurinfo/v2/2_studies_migration.py
  docker-compose/migration/ofsep/2_studies_migration.py
  docker-compose/migration/ofsep/2_studies_tables.sql
  docker-compose/migration_scripts/Neurinfo/2_studies_migration.py
  docker-compose/migration_scripts/OFSEP/2_studies_migration.py
  shanoir-ng-front/src/app/centers/shared/center.service.ts
  shanoir-ng-front/src/app/import/bids/bids-upload.component.html
  shanoir-ng-front/src/app/import/bids/bids-upload.component.ts
  shanoir-ng-front/src/app/studies/shared/study.dto.ts
  shanoir-ng-front/src/app/studies/shared/study.model.ts
  shanoir-ng-front/src/app/studies/study/study.component.html
  shanoir-ng-front/src/app/studies/study/study.component.ts
  shanoir-ng-studies/src/main/docker/files/opt/cfg/shanoirng_studies.sql
  shanoir-ng-studies/src/main/docker/files/opt/cfg/shanoirng_studies_tables.sql
  shanoir-ng-studies/src/main/docker/files/opt/cfg/studiesMigration.py
  shanoir-ng-studies/src/main/docker/files/opt/cfg/studies_migration_v2.0.1.py
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/dto/StudyDTO.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/model/Study.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/security/StudySecurityService.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/service/RelatedDatasetServiceImpl.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/service/StudyServiceImpl.java
  shanoir-ng-studies/src/main/java/org/shanoir/ng/studycenter/StudyCenter.java
  shanoir-ng-studies/src/main/resources/scripts/import.sql
  shanoir-ng-studies/src/main/resources/scripts/test-data-h2.sql
Labels: bug, study, REVIEWABLE
