Repository fli-iam/shanoir-ng, pull requests merged in 2025-03, with the labels that each got.

#2541 #2506 : dataset tag API created (add/remove tags to a dataset only)
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApi.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/tag/controller/StudyTagApi.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/tag/controller/StudyTagApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/tag/service/StudyTagService.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/dataset/StudyTagApiControllerTest.java
Labels: REVIEWABLE

#2564 Allowing autocompletion on JComboBoxes for study cards and subjects
  shanoir-uploader/pom.xml
  shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportDialogOpener.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportStudyAndStudyCardCBItemListener.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/action/ImportStudyCardFilterDocumentListener.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/gui/ImportDialog.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/model/rest/Subject.java
  shanoir-uploader/src/main/resources/messages_en.properties
  shanoir-uploader/src/main/resources/messages_fr.properties
Labels: REVIEWABLE

#2728 shanoir-issue#2722: fix study.profile in mass exam import
  shanoir-ng-front/src/app/studies/shared/study.dto.ts
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/dto/StudyLightDTO.java
Labels: import, REVIEWABLE

#2672 #2618 : Solr indexation not blocking anymore when failed
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/configuration/RabbitMQDatasetsService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/importer/service/DicomSEGAndSRImporterService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/controler/SolrApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/service/SolrService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/solr/service/SolrServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/studycard/controler/StudyCardApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/vip/output/handler/OFSEPSeqIdHandler.java
Labels: REVIEWABLE

#2739 shanoir-issue#2738: add JsonIgnore on profile field
  shanoir-ng-studies/src/main/java/org/shanoir/ng/study/repository/StudyRepository.java
Labels: REVIEWABLE

#2676 fix performance issues with lots of subject nodes
  shanoir-ng-front/src/app/app.component.css
  shanoir-ng-front/src/app/preclinical/extraData/extraData/shared/extradata.service.ts
  shanoir-ng-front/src/app/studies/study/study-tree.component.ts
  shanoir-ng-front/src/app/studies/study/tree.service.ts
  shanoir-ng-front/src/app/studies/tree/study-node.component.css
  shanoir-ng-front/src/app/studies/tree/study-node.component.html
  shanoir-ng-front/src/app/studies/tree/study-node.component.ts
  shanoir-ng-front/src/app/tree/tree.model.ts
Labels: next-release

#2756 shanoir-issue#2750: fix statistics procedure
  docker-compose/database/db-changes/datasets/0057_add_statistics_procedure.sql
Labels: OFSEP, BUGFIX, REVIEWABLE
