Repository fli-iam/shanoir-ng, pull requests merged in 2025-07, with the labels that each got.

#2898 ShUp - add a tooltip icon to inform users
  shanoir-uploader/src/main/java/org/shanoir/uploader/gui/MainWindow.java
  shanoir-uploader/src/main/resources/images/info.png
  shanoir-uploader/src/main/resources/messages_en.properties
  shanoir-uploader/src/main/resources/messages_fr.properties
Labels: ShanoirUploader

#2795 ShUp: examination consistency checker
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/DICOMWebApi.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/service/DICOMWebService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationServiceImpl.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/ImporterManagerService.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/DicomDirGeneratorService.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/DicomUtils.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/dicom/ImagesCreatorAndDicomFileAnalyzerService.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/model/Instance.java
  shanoir-ng-import/src/main/java/org/shanoir/ng/importer/model/UploadState.java
  shanoir-uploader/pom.xml
  shanoir-uploader/src/main/java/org/shanoir/uploader/ShUpConfig.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/action/init/ReadyState.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/action/init/SelectProfilePanelActionListener.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/check/ExaminationConsistencyServiceJob.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/gui/CurrentUploadsWindowTable.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/gui/MainWindow.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/nominativeData/CurrentNominativeDataController.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/service/rest/HttpService.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/service/rest/ShanoirUploaderServiceClient.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/upload/UploadServiceJob.java
  shanoir-uploader/src/main/java/org/shanoir/uploader/utils/PropertiesUtil.java
  shanoir-uploader/src/main/resources/basic.properties
  shanoir-uploader/src/main/resources/messages_en.properties
  shanoir-uploader/src/main/resources/messages_fr.properties
  shanoir-uploader/src/test/java/org/shanoir/uploader/test/importer/ZipFileImportTest.java
Labels: ShanoirUploader, REVIEWABLE

#2887 #2881 : correcting some field checks for center form creation/edition
  shanoir-ng-front/src/app/centers/center/center.component.html
  shanoir-ng-front/src/app/centers/center/center.component.ts
  shanoir-ng-front/src/app/shared/validators/shanoir-validators.ts
Labels: frontend, feature, REVIEWABLE

#2886 #NOISSUE : shared shanoir-validators creation
  shanoir-ng-front/src/app/shared/validators/shanoir-validators.ts
Labels: frontend, REVIEWABLE

#2927 get tag associated with last NG release
  .github/workflows/shup_release.yml
Labels: ShanoirUploader

#2733 shanoir-issue#2729: fix unique equipment validator
  shanoir-ng-front/src/app/acquisition-equipments/acquisition-equipment/acquisition-equipment.component.ts
  shanoir-ng-front/src/app/acquisition-equipments/shared/acquisition-equipment.service.ts
Labels: frontend, REVIEWABLE

#2929 Vip features to merge
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApi.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/repository/DatasetRepository.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetDownloaderServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/processing/service/ProcessingDownloaderServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/utils/DatasetFileUtils.java
Labels: backend, BUGFIX, VIP
