Repository fli-iam/shanoir-ng, pull requests merged in 2025-02, with the labels that each got.

#2637 shanoir-issue#2635: fix get size procedure
  docker-compose/database/3_add_statistics_procedure.sql
  docker-compose/database/db-changes/datasets/0056_add_statistics_procedure.sql
Labels: bug, datasets, REVIEWABLE

#2602 shanoir-issue#2601: fix delete from pacs
  shanoir-ng-anonymization/src/main/resources/anonymization.xlsx
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/service/DatasetAcquisitionService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/service/DatasetAcquisitionServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/SeriesInstanceUIDHandler.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/StudyInstanceUIDHandler.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/service/DICOMWebService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/examination/service/ExaminationServiceImpl.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/dataset/DatasetApiSecurityTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/dataset/DatasetServiceSecurityTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/datasetacquisition/DatasetAcquisitionServiceSecurityTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/examination/ExaminationApiSecurityTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/examination/ExaminationServiceSecurityTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/examination/ExaminationServiceTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/importer/strategies/protocol/MrProtocolStrategyTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/processing/resulthandler/output/DefaultHandlerTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/processing/resulthandler/output/OFSEPSeqIdProcessingTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/studycard/StudyCardApiSecurityTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/studycard/StudyCardRepositoryTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/studycard/StudyCardSecurityTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/studycard/StudyCardServiceSecurityTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/studycard/StudyCardServiceTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/studyuser/StudyUserProcessCommandTest.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/tasks/ShanoirEventServiceTest.java
  shanoir-ng-front/src/app/studies/tree/reverse-study-node.component.ts
Labels: REVIEWABLE

#2663 Try to optimize delete dataset
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/controler/DatasetApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/DICOMWebApiController.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dicom/web/service/DICOMWebService.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/dataset/DatasetServiceSecurityTest.java
Labels: REVIEWABLE

#2668 shanoir-issue#2658: delete dataset
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetAsyncService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetAsyncServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetService.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/dataset/service/DatasetServiceImpl.java
  shanoir-ng-datasets/src/main/java/org/shanoir/ng/datasetacquisition/dto/mapper/DatasetAcquisitionDatasetsMapper.java
  shanoir-ng-datasets/src/test/java/org/shanoir/ng/dataset/DatasetServiceSecurityTest.java
  shanoir-ng-front/src/app/shared/side-menu/side-menu.component.html
  shanoir-ng-users/src/main/java/org/shanoir/ng/events/ShanoirEventsService.java
  shanoir-ng-users/src/main/java/org/shanoir/ng/tasks/AsyncTaskApiController.java
Labels: WorkInProgress, next-release
